### ISSUE TITLE
HTTP Port is already in use

### ISSUE THREAD

**Issue by RedstoneCommands** [Minary/Tools#1]
Hey there, everytime i try to start an "Attack" i get the following Error Pop up. How do i fix this?
![error](https://user-images.githubusercontent.com/30706293/33771733-6bb76be2-dc32-11e7-8b60-b7958d1188fb.PNG)

**Comment by rubenunteregger** [comment]
This is a notification from Minary itself. Another application is using port 80 which conflicts with Minary's HttpReverseProxyServer. You first have to stop that application before you can use Minary.
